import path from "node:path";
import fs from "node:fs/promises";
import type { CommandRequest, CommandResponse } from "./types.js";
import { getContext, getActivePage, setActivePage } from "./server.js";
import { captureSnapshot } from "./snapshot.js";

function page() {
  const p = getActivePage();
  if (!p) throw new Error("No active page. Use 'navigate' to open a page, or 'tab-new' to create one.");
  return p;
}

/** Get or create a page — used by navigate when no page exists */
async function pageOrCreate() {
  let p = getActivePage();
  if (!p) {
    const c = ctx();
    p = await c.newPage();
    setActivePage(p);
  }
  return p;
}

function ctx() {
  const c = getContext();
  if (!c) throw new Error("No browser context.");
  return c;
}

/**
 * Resolve a ref like "e2" to a Playwright locator using the aria-ref selector.
 * Refs are generated by ariaSnapshot({ mode: "ai" }) and are only valid until
 * the page DOM changes significantly.
 */
function locatorForRef(ref: string) {
  return page().locator(`aria-ref=${ref}`);
}

export async function handleCommand(req: CommandRequest): Promise<CommandResponse> {
  try {
    const result = await dispatch(req.command, req.args);
    return { ok: true, result };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

async function dispatch(command: string, args: Record<string, unknown>): Promise<unknown> {
  switch (command) {
    // ── Navigation ──────────────────────────────────────────────
    case "navigate": {
      const url = String(args.url);
      const p = await pageOrCreate();
      await p.goto(url, { waitUntil: "domcontentloaded" });
      return { url: p.url(), title: await p.title() };
    }
    case "back": {
      await page().goBack({ waitUntil: "commit" });
      return { url: page().url(), title: await page().title() };
    }
    case "forward": {
      await page().goForward({ waitUntil: "commit" });
      return { url: page().url(), title: await page().title() };
    }
    case "reload": {
      await page().reload({ waitUntil: "domcontentloaded" });
      return { url: page().url(), title: await page().title() };
    }

    // ── Observation ─────────────────────────────────────────────
    case "snapshot": {
      const tree = await captureSnapshot(page(), {
        depth: args.depth as number | undefined,
      });
      return {
        url: page().url(),
        title: await page().title(),
        tree,
      };
    }
    case "screenshot": {
      const screenshotOpts: Record<string, unknown> = {
        type: "jpeg" as const,
        quality: 75,
      };
      if (args.fullPage) screenshotOpts.fullPage = true;

      let buffer: Buffer;
      if (args.ref) {
        const locator = locatorForRef(String(args.ref));
        buffer = await locator.screenshot(screenshotOpts);
      } else {
        buffer = await page().screenshot(screenshotOpts);
      }

      // Save to a temp file so Claude can read the image via the Read tool
      const os = await import("node:os");
      const tmpFile = path.join(os.tmpdir(), `browser-screenshot-${Date.now()}.jpg`);
      await fs.writeFile(tmpFile, buffer);
      return { file: tmpFile, size: buffer.length };
    }

    // ── Interaction (ref-based) ─────────────────────────────────
    case "click": {
      if (args.ref) {
        const locator = locatorForRef(String(args.ref));
        if (args.doubleClick) {
          await locator.dblclick();
        } else {
          await locator.click();
        }
        return { clicked: args.ref };
      }
      throw new Error("click requires a ref. Use click-xy for coordinate-based clicking.");
    }
    case "click-xy": {
      const x = Number(args.x);
      const y = Number(args.y);
      await page().mouse.click(x, y);
      return { clicked: { x, y } };
    }
    case "type": {
      const ref = String(args.ref);
      const text = String(args.text);
      const locator = locatorForRef(ref);
      await locator.fill(text);
      if (args.submit) {
        await locator.press("Enter");
      }
      return { typed: text, ref, submitted: !!args.submit };
    }
    case "fill": {
      const fields = args.fields as Array<{ ref: string; value: string }>;
      if (!Array.isArray(fields)) throw new Error("fill requires a fields array");
      for (const { ref, value } of fields) {
        const locator = locatorForRef(ref);
        await locator.fill(value);
      }
      return { filled: fields.length };
    }
    case "select": {
      const locator = locatorForRef(String(args.ref));
      const values = Array.isArray(args.values) ? args.values.map(String) : [String(args.value)];
      await locator.selectOption(values);
      return { selected: values, ref: args.ref };
    }
    case "hover": {
      const locator = locatorForRef(String(args.ref));
      await locator.hover();
      return { hovered: args.ref };
    }
    case "drag": {
      const source = locatorForRef(String(args.fromRef));
      const target = locatorForRef(String(args.toRef));
      await source.dragTo(target);
      return { dragged: { from: args.fromRef, to: args.toRef } };
    }
    case "press": {
      const key = String(args.key);
      await page().keyboard.press(key);
      return { pressed: key };
    }

    // ── Coordinate-based interaction ────────────────────────────
    case "mouse-move": {
      await page().mouse.move(Number(args.x), Number(args.y));
      return { moved: { x: args.x, y: args.y } };
    }
    case "mouse-down": {
      await page().mouse.down();
      return { mouseDown: true };
    }
    case "mouse-up": {
      await page().mouse.up();
      return { mouseUp: true };
    }
    case "scroll": {
      const deltaX = Number(args.deltaX ?? 0);
      const deltaY = Number(args.deltaY ?? 0);
      await page().mouse.wheel(deltaX, deltaY);
      return { scrolled: { deltaX, deltaY } };
    }

    // ── Wait ────────────────────────────────────────────────────
    case "wait": {
      if (args.text) {
        const text = String(args.text);
        if (args.gone) {
          await page().waitForSelector(`text=${text}`, { state: "hidden" });
          return { waitedForGone: text };
        }
        await page().waitForSelector(`text=${text}`, { state: "visible" });
        return { waitedFor: text };
      }
      if (args.time) {
        const ms = Number(args.time);
        await new Promise((r) => setTimeout(r, ms));
        return { waited: ms };
      }
      throw new Error("wait requires either text or time");
    }

    // ── JavaScript evaluation ───────────────────────────────────
    case "evaluate": {
      const expression = String(args.expression);
      const result = await page().evaluate(expression);
      return { result };
    }

    // ── Tabs ────────────────────────────────────────────────────
    case "tabs": {
      const pages = ctx().pages();
      const active = getActivePage();
      return {
        tabs: await Promise.all(
          pages.map(async (p, i) => ({
            index: i,
            url: p.url(),
            title: await p.title(),
            active: p === active,
          }))
        ),
      };
    }
    case "tab": {
      const index = Number(args.index);
      const pages = ctx().pages();
      if (index < 0 || index >= pages.length) {
        throw new Error(`Tab index ${index} out of range (0-${pages.length - 1})`);
      }
      setActivePage(pages[index]);
      await pages[index].bringToFront();
      return { switched: index, url: pages[index].url() };
    }
    case "tab-new": {
      const newPage = await ctx().newPage();
      if (args.url) {
        await newPage.goto(String(args.url), { waitUntil: "domcontentloaded" });
      }
      setActivePage(newPage);
      return { opened: true, url: newPage.url() };
    }
    case "tab-close": {
      const pages = ctx().pages();
      const idx = args.index !== undefined ? Number(args.index) : pages.indexOf(page());
      if (idx < 0 || idx >= pages.length) throw new Error(`Invalid tab index ${idx}`);
      await pages[idx].close();
      const remaining = ctx().pages();
      if (remaining.length > 0) {
        setActivePage(remaining[remaining.length - 1]);
      }
      return { closed: idx, remaining: remaining.length };
    }

    // ── Viewport ────────────────────────────────────────────────
    case "resize": {
      const width = Number(args.width);
      const height = Number(args.height);
      await page().setViewportSize({ width, height });
      return { resized: { width, height } };
    }

    // ── File upload ─────────────────────────────────────────────
    case "upload": {
      const locator = locatorForRef(String(args.ref));
      const paths = (args.paths as string[]).map((p) => path.resolve(p));
      await locator.setInputFiles(paths);
      return { uploaded: paths };
    }

    // ── Storage ─────────────────────────────────────────────────
    case "storage-save": {
      const file = path.resolve(String(args.file));
      const state = await ctx().storageState();
      await fs.writeFile(file, JSON.stringify(state, null, 2));
      return { saved: file };
    }
    case "storage-load": {
      const file = path.resolve(String(args.file));
      const raw = await fs.readFile(file, "utf-8");
      const state = JSON.parse(raw);
      if (state.cookies) {
        await ctx().addCookies(state.cookies);
      }
      if (state.origins) {
        for (const origin of state.origins) {
          if (origin.localStorage?.length) {
            const p = await ctx().newPage();
            await p.goto(origin.origin);
            for (const { name, value } of origin.localStorage) {
              await p.evaluate(
                ([k, v]) => localStorage.setItem(k, v),
                [name, value]
              );
            }
            await p.close();
          }
        }
      }
      return { loaded: file };
    }

    // ── Cookies ─────────────────────────────────────────────────
    case "cookie-list": {
      let cookies = await ctx().cookies();
      if (args.domain) {
        const domain = String(args.domain);
        cookies = cookies.filter((c) => c.domain.includes(domain));
      }
      return { cookies };
    }
    case "cookie-set": {
      await ctx().addCookies([
        {
          name: String(args.name),
          value: String(args.value),
          domain: args.domain as string | undefined,
          path: (args.path as string) ?? "/",
          url: args.url as string | undefined,
        },
      ]);
      return { set: args.name };
    }
    case "cookie-clear": {
      await ctx().clearCookies();
      return { cleared: true };
    }

    // ── localStorage ────────────────────────────────────────────
    case "localstorage-get": {
      const val = await page().evaluate((k) => localStorage.getItem(k), String(args.key));
      return { key: args.key, value: val };
    }
    case "localstorage-set": {
      await page().evaluate(
        ([k, v]) => localStorage.setItem(k, v),
        [String(args.key), String(args.value)]
      );
      return { set: args.key };
    }
    case "localstorage-list": {
      const items = await page().evaluate(() => {
        const result: Record<string, string> = {};
        for (let i = 0; i < localStorage.length; i++) {
          const k = localStorage.key(i)!;
          result[k] = localStorage.getItem(k)!;
        }
        return result;
      });
      return { items };
    }

    // ── Server ──────────────────────────────────────────────────
    case "status": {
      const p = getActivePage();
      return {
        connected: !!p,
        url: p?.url() ?? null,
        title: p ? await p.title() : null,
        tabs: ctx()?.pages().length ?? 0,
      };
    }

    default:
      throw new Error(`Unknown command: ${command}`);
  }
}
